FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y git git-core python-pip python-dev build-essential libssl-dev curl

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 7.1.0

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN pip install --upgrade pip

WORKDIR /work

COPY requirements.txt .

RUN pip install -t vendored/ -r requirements.txt

RUN npm install -g serverless

ADD . .

CMD ./deploy-serverless.sh
