service: sportnumerics-predict
provider:
  name: aws
  stage: dev
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "ecs:RunTask"
    Resource:
      - Ref: PredictTask
  - Effect: "Allow"
    Action:
      - "iam:PassRole"
    Resource:
      - Fn::GetAtt: [TaskExecutionRole, Arn]
      - Fn::GetAtt: [TaskRole, Arn]
package:
  exclude:
  - config/env.sh
custom:
  teamsBucketName: ${cf:sportnumerics-stats-${opt:stage}.ResultsBucketName}
  teamsBucketArn: "arn:aws:s3:::${self:custom.teamsBucketName}"

resources: ${file(resources.yml)}

functions:
  predict:
    handler: bootstrap.handler
    runtime: python2.7
    timeout: 120
    environment:
      ECS_CLUSTER:
        Ref: Cluster
      ECS_TASK:
        Ref: PredictTask
