service: sportnumerics-predict
provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "ecs:RunTask"
      - "ecs:DescribeClusters"
    Resource:
      - Ref: PredictTask
      - Ref: Cluster
  - Effect: "Allow"
    Action: "autoscaling:SetDesiredCapacity"
    Resource: "*"
package:
  exclude:
  - config/env.sh
custom:
  resultsBucketName: sportnumerics-predict-${opt:stage}
  resultsBucketArn: arn:aws:s3:::${self:custom.resultsBucketName}
  snsTopicName: sportnumerics-predict-${opt:stage}
  snsTopicArn:
    Fn::Join:
      - ':'
      - - 'arn:aws:sns'
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - ${self:custom.snsTopicName}

resources: ${file(resources.yml)}

functions:
  predict:
    handler: bootstrap.handler
    runtime: python2.7
    events:
    - sns:
        topicName: ${self:custom.snsTopicName}
        displayName: "Stats Collection Routing"
    environment:
      ECS_CLUSTER:
        Ref: Cluster
      ECS_TASK:
        Ref: PredictTask
      AS_GROUP_NAME:
        Ref: AutoScalingGroup
