service: sportnumerics-predict
provider:
  name: aws
  stage: dev
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "ecs:RunTask"
      - "ecs:DescribeClusters"
    Resource:
      - Ref: PredictTask
      - Fn::Join:
          - ':'
          - - 'arn:aws:ecs'
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - Fn::Join:
              - '/'
              - - 'cluster'
                - Ref: Cluster
  - Effect: "Allow"
    Action: "autoscaling:SetDesiredCapacity"
    Resource: "*"
package:
  exclude:
  - config/env.sh
custom:
  teamsTableName: ${cf:sportnumerics-stats-${opt:stage}.TeamsTableName}
  teamsTableArn:
    Fn::Join:
    - ":"
    - - "arn:aws:dynamodb"
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.teamsTableName}

resources: ${file(resources.yml)}

functions:
  predict:
    handler: bootstrap.handler
    runtime: python2.7
    timeout: 120
    environment:
      ECS_CLUSTER:
        Ref: Cluster
      ECS_TASK:
        Ref: PredictTask
      AS_GROUP_NAME:
        Ref: AutoScalingGroup
