service: sportnumerics
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: ${self:custom.resultsBucketArn}
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource: "${self:custom.resultsBucketArn}/*"
  environment:
    RESULTS_BUCKET_NAME: ${self.custom.resultsBucketName}
    DATASOURCE_HOST: sportnumerics-stats-${opt:stage}.s3-website-ap-southeast-2.amazonaws.com
package:
  exclude:
  - config/env.sh
custom:
  resultsBucketName: sportnumerics-predict-${opt:stage}
  resultsBucketArn:
    Fn::Join:
      - ':'
      - - 'arn:aws:s3'
        - ':'
        - '${self:custom.resultsBucketName}'
  snsTopicName: sportnumerics-predict-${opt:stage}
  snsTopicArn:
    Fn::Join:
      - ':'
      - - 'arn:aws:sns'
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - ${self:custom.snsTopicName}

resources:
  Resources:
    S3BucketPredict:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.resultsBucketName}
        AccessControl: "PublicRead"

functions:
  predict:
    handler: go.run
    events:
    - sns:
        topicName: ${self:custom.snsTopicName}
        displayName: "Stats Collection Routing"
